<a href="https://colab.research.google.com/github/MiguelFigueroa02/Challenge_Telecom_X_Evasion_Clientes/blob/main/telecomx_latam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ðŸ“Œ ExtracciÃ³n

## Conociendo los datos

### Carga de la informaciÃ³n

In [338]:
import pandas as pd
import requests

In [339]:
url = 'https://raw.githubusercontent.com/MiguelFigueroa02/Challenge_Telecom_X_Evasion_Clientes/refs/heads/main/TelecomX_Data.json'
data = requests.get(url)

In [340]:
data = data.json()

In [341]:
datos = pd.DataFrame(data)

In [342]:
datos.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [343]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [344]:
from pandas import json_normalize
datos_normalizados = json_normalize(data)
datos_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

Vamos a asegurarnos que la columna CustomerID no cuente con registros duplicados

In [345]:
datos_normalizados['customerID'].duplicated().sum()

np.int64(0)

No se encuentran registros duplicados

In [346]:
datos_normalizados['customerID'].isnull().sum()

np.int64(0)

Para empezar, hago un anÃ¡lisis sobre la columna Churn

In [347]:
datos_normalizados['Churn'].unique()

array(['No', 'Yes', ''], dtype=object)

Exploro valores vacÃ­os

In [348]:
datos_normalizados.query('Churn == ""')

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
30,0047-ZHDTW,,Female,0,No,No,11,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),79.00,929.3
75,0120-YZLQA,,Male,0,No,No,71,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),19.90,1355.1
96,0154-QYHJU,,Male,0,No,No,29,Yes,No,DSL,...,Yes,No,Yes,No,No,One year,Yes,Electronic check,58.75,1696.2
98,0162-RZGMZ,,Female,1,No,No,5,Yes,No,DSL,...,Yes,No,Yes,No,No,Month-to-month,No,Credit card (automatic),59.90,287.85
175,0274-VVQOQ,,Male,1,Yes,No,65,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,Yes,One year,Yes,Bank transfer (automatic),103.15,6792.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7158,9840-GSRFX,,Female,0,No,No,14,Yes,Yes,DSL,...,Yes,No,No,No,No,One year,Yes,Mailed check,54.25,773.2
7180,9872-RZQQB,,Female,0,Yes,No,49,No,No phone service,DSL,...,No,No,No,Yes,No,Month-to-month,No,Bank transfer (automatic),40.65,2070.75
7211,9920-GNDMB,,Male,0,No,No,9,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,76.25,684.85
7239,9955-RVWSC,,Female,0,Yes,Yes,67,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),19.25,1372.9
7247,9966-VYRTZ,,Female,0,Yes,Yes,31,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.55,658.95

Dado que el status de los clientes con valores vacÃ­os aÃºn no estÃ¡ definido, se toma como si la decisiÃ³n de dejar o no la compaÃ±Ã­a no ha sido tomada por los clientes. Por lo cual, estos mantienen el status de sus servicios vigentes hasta que sea tomada una decisiÃ³n.

Para detectar valores positivos, negativos y nulos, se convierte resultados a tipo booleano y los resultados vaciios se convierten a null

In [349]:
datos_normalizados['Churn'] = datos_normalizados['Churn'].replace('Yes',True).replace('No',False)

In [350]:
datos_normalizados['Churn'] = datos_normalizados['Churn'].replace('',None)

In [351]:
datos_normalizados['Churn'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 7267 entries, 0 to 7266
Series name: Churn
Non-Null Count  Dtype
--------------  -----
7043 non-null   object
dtypes: object(1)
memory usage: 56.9+ KB

Se detectan 223 valores vacÃ­os, los cuales se convierten a nulos.

## EvaluaciÃ³n de la informaciÃ³ adicional

Verifico el tipo de datos Ãºnicos para determinar el tratamiento a realizar

In [352]:
columnas_customer = list(datos_normalizados.columns)
columnas_customer
for columna in columnas_customer:
  mensaje = f'En la columna {columna} se encuentran un total de {datos_normalizados[columna].nunique()} valores Ãºnicos.'
  if datos_normalizados[columna].nunique() < 50:
    mensaje = mensaje + f'\n Los valores Ãºnicos son {datos_normalizados[columna].unique()}'
  print(mensaje)
  print('-'* 50)

En la columna customerID se encuentran un total de 7267 valores Ãºnicos.
--------------------------------------------------
En la columna Churn se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son [False True None]
--------------------------------------------------
En la columna customer.gender se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son ['Female' 'Male']
--------------------------------------------------
En la columna customer.SeniorCitizen se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son [0 1]
--------------------------------------------------
En la columna customer.Partner se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No']
--------------------------------------------------
En la columna customer.Dependents se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No']
--------------------------------------------------
En la columna customer.tenure se encuentran un total de 73 valores Ãºnicos.
--------------------------------------------------
En la columna phone.PhoneService se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No']
--------------------------------------------------
En la columna phone.MultipleLines se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['No' 'Yes' 'No phone service']
--------------------------------------------------
En la columna internet.InternetService se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['DSL' 'Fiber optic' 'No']
--------------------------------------------------
En la columna internet.OnlineSecurity se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['No' 'Yes' 'No internet service']
--------------------------------------------------
En la columna internet.OnlineBackup se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No' 'No internet service']
--------------------------------------------------
En la columna internet.DeviceProtection se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['No' 'Yes' 'No internet service']
--------------------------------------------------
En la columna internet.TechSupport se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No' 'No internet service']
--------------------------------------------------
En la columna internet.StreamingTV se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No' 'No internet service']
--------------------------------------------------
En la columna internet.StreamingMovies se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['No' 'Yes' 'No internet service']
--------------------------------------------------
En la columna account.Contract se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['One year' 'Month-to-month' 'Two year']
--------------------------------------------------
En la columna account.PaperlessBilling se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No']
--------------------------------------------------
En la columna account.PaymentMethod se encuentran un total de 4 valores Ãºnicos.
 Los valores Ãºnicos son ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
--------------------------------------------------
En la columna account.Charges.Monthly se encuentran un total de 1585 valores Ãºnicos.
--------------------------------------------------
En la columna account.Charges.Total se encuentran un total de 6531 valores Ãºnicos.
--------------------------------------------------

Voy a ver cuÃ¡ntas en las cuÃ¡ntos valores vacÃ­os existe en cada una de las columnas

In [353]:
columnas_normalizadas = list(datos_normalizados.columns)
columnas_normalizadas

['customerID',
 'Churn',
 'customer.gender',
 'customer.SeniorCitizen',
 'customer.Partner',
 'customer.Dependents',
 'customer.tenure',
 'phone.PhoneService',
 'phone.MultipleLines',
 'internet.InternetService',
 'internet.OnlineSecurity',
 'internet.OnlineBackup',
 'internet.DeviceProtection',
 'internet.TechSupport',
 'internet.StreamingTV',
 'internet.StreamingMovies',
 'account.Contract',
 'account.PaperlessBilling',
 'account.PaymentMethod',
 'account.Charges.Monthly',
 'account.Charges.Total']

In [354]:
for columna in columnas_normalizadas:
  valor = None
  valor = datos_normalizados[columna].isin(['',' ',None,'False']).sum()
  if valor > 0:
    print(f'La columna {columna} tiene {valor} valores vacÃ­os ''o iguales a none')

La columna Churn tiene 224 valores vacÃ­os o iguales a none
La columna account.Charges.Total tiene 11 valores vacÃ­os o iguales a none

EvalÃºo el comportamiento sobre la columna account.Charges.Total para los valores vacÃ­os.

In [355]:
datos_normalizados[
    (datos_normalizados['account.Charges.Total'].isin(['',' ', False, 'False'])) |
    (datos_normalizados['account.Charges.Total'].isna())
]

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
975,1371-DWPAZ,False,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,False,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,False,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,False,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,False,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,False,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,False,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,False,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,False,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,False,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,False,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

Puesto que se encuentra una relaciÃ³n directa sobre de estas columnas, las cuales tienen una antigÃ¼edad de 0 meses de contrato, los valores de la columna account.Charges.Total se convertirÃ¡n a cero dado que aÃºn no ha llegado un gasto para estos usuarios.

In [356]:
datos_normalizados['account.Charges.Total'] = datos_normalizados['account.Charges.Total'].apply(lambda x: 0 if str(x).strip() in ['','False',False] else x)

Se convierte a tipo numÃ©rico

In [357]:
import numpy as np

In [358]:
datos_normalizados['account.Charges.Total'] = datos_normalizados['account.Charges.Total'].astype(np.float64)
datos_normalizados['account.Charges.Total'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 7267 entries, 0 to 7266
Series name: account.Charges.Total
Non-Null Count  Dtype
--------------  -----
7267 non-null   float64
dtypes: float64(1)
memory usage: 56.9 KB

Se hace una modificaciÃ³n  para que las columnas con valores Ãºnicos 'Yes' y 'No' Ã³ 0 y 1 se conviertan a tipo booleano, con valores True y False

In [359]:
columnas_bool = ['customer.SeniorCitizen','customer.Partner','customer.Dependents','phone.PhoneService','account.PaperlessBilling']

In [360]:
for columna in columnas_bool:
  datos_normalizados[columna] = datos_normalizados[columna].apply(lambda x: True if x in [1,'Yes'] else x).apply(lambda y: False if y in [0,'No'] else y)

In [361]:
datos_normalizados[columnas_bool].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer.SeniorCitizen    7267 non-null   bool
 1   customer.Partner          7267 non-null   bool
 2   customer.Dependents       7267 non-null   bool
 3   phone.PhoneService        7267 non-null   bool
 4   account.PaperlessBilling  7267 non-null   bool
dtypes: bool(5)
memory usage: 35.6 KB

Se ejecuta funciÃ³n para verificar nuevamente valores Ãºnicos en todas las columnas

In [362]:
columnas_customer = list(datos_normalizados.columns)
columnas_customer
for columna in columnas_customer:
  mensaje = f'En la columna {columna} es del tipo {datos_normalizados[columna].dtype} se encuentran un total de {datos_normalizados[columna].nunique()} valores Ãºnicos.'
  if datos_normalizados[columna].nunique() < 50:
    mensaje = mensaje + f'\n Los valores Ãºnicos son {datos_normalizados[columna].unique()}'
  print(mensaje)
  print('-'* 50)

En la columna customerID es del tipo object se encuentran un total de 7267 valores Ãºnicos.
--------------------------------------------------
En la columna Churn es del tipo object se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son [False True None]
--------------------------------------------------
En la columna customer.gender es del tipo object se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son ['Female' 'Male']
--------------------------------------------------
En la columna customer.SeniorCitizen es del tipo bool se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son [False  True]
--------------------------------------------------
En la columna customer.Partner es del tipo bool se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son [ True False]
--------------------------------------------------
En la columna customer.Dependents es del tipo bool se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son [ True False]
--------------------------------------------------
En la columna customer.tenure es del tipo int64 se encuentran un total de 73 valores Ãºnicos.
--------------------------------------------------
En la columna phone.PhoneService es del tipo bool se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son [ True False]
--------------------------------------------------
En la columna phone.MultipleLines es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['No' 'Yes' 'No phone service']
--------------------------------------------------
En la columna internet.InternetService es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['DSL' 'Fiber optic' 'No']
--------------------------------------------------
En la columna internet.OnlineSecurity es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['No' 'Yes' 'No internet service']
--------------------------------------------------
En la columna internet.OnlineBackup es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No' 'No internet service']
--------------------------------------------------
En la columna internet.DeviceProtection es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['No' 'Yes' 'No internet service']
--------------------------------------------------
En la columna internet.TechSupport es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No' 'No internet service']
--------------------------------------------------
En la columna internet.StreamingTV es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['Yes' 'No' 'No internet service']
--------------------------------------------------
En la columna internet.StreamingMovies es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['No' 'Yes' 'No internet service']
--------------------------------------------------
En la columna account.Contract es del tipo object se encuentran un total de 3 valores Ãºnicos.
 Los valores Ãºnicos son ['One year' 'Month-to-month' 'Two year']
--------------------------------------------------
En la columna account.PaperlessBilling es del tipo bool se encuentran un total de 2 valores Ãºnicos.
 Los valores Ãºnicos son [ True False]
--------------------------------------------------
En la columna account.PaymentMethod es del tipo object se encuentran un total de 4 valores Ãºnicos.
 Los valores Ãºnicos son ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
--------------------------------------------------
En la columna account.Charges.Monthly es del tipo float64 se encuentran un total de 1585 valores Ãºnicos.
--------------------------------------------------
En la columna account.Charges.Total es del tipo float64 se encuentran un total de 6531 valores Ãºnicos.
--------------------------------------------------

Se verifican los valores en la columna phone.MultipleLines para determinar si existe alguno diferente a 'No phone service' si no se cuenta con servicio telefÃ³nico para verificar que no existan inconsistencias.

In [364]:
datos_normalizados[(datos_normalizados['phone.MultipleLines'] == 'No phone service')]['phone.PhoneService'].unique()

array([False])

In [365]:
datos_normalizados[(datos_normalizados['phone.MultipleLines'] != 'No phone service')]['phone.PhoneService'].unique()

array([ True])

In [366]:
datos_normalizados['phone.MultipleLines'].apply(lambda x: 'No' if str(x).strip() == 'No phone service' else x).unique()

array(['No', 'Yes'], dtype=object)

Se convierten datos a tipo booleano

In [368]:
datos_normalizados['phone.MultipleLines'] = datos_normalizados['phone.MultipleLines'].apply(lambda x: False if str(x).strip() in ['No phone service', 'No'] else x).apply(lambda y: True if str(y).strip()== 'Yes' else y)

In [370]:
datos_normalizados['phone.MultipleLines'].unique()

array([False,  True])